# Generated by Django 6.0.2 on 2026-03-25 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0007_invoice_subscription'),
        ('workout', '0004_trainerprofile_traineravailability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('calories_burn_estimate', models.PositiveIntegerField(default=300)),
                ('difficulty', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='class_types/')),
                ('equipment_needed', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fitx_class_types',
            },
        ),
        migrations.CreateModel(
            name='FitnessCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('amenities', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(default='05:00')),
                ('closing_time', models.TimeField(default='23:00')),
            ],
            options={
                'db_table': 'fitx_centers',
                'indexes': [models.Index(fields=['city', 'is_active'], name='fitx_center_city_9d57f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_capacity', models.PositiveIntegerField(default=30)),
                ('current_bookings', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_url', models.URLField(blank=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='workout.trainerprofile')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='booking.classtype')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to='booking.fitnesscenter')),
            ],
            options={
                'db_table': 'fitx_class_schedules',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='booking.classschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fitx_waitlist',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('waitlist_position', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('payment_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='store.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.classschedule')),
            ],
            options={
                'db_table': 'fitx_bookings',
                'indexes': [models.Index(fields=['user', 'status'], name='fitx_bookin_user_id_ab4a85_idx'), models.Index(fields=['class_schedule', 'status'], name='fitx_bookin_class_s_c2c3f8_idx')],
                'unique_together': {('user', 'class_schedule')},
            },
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['date', 'start_time', 'status'], name='fitx_class__date_c60815_idx'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['center', 'date'], name='fitx_class__center__69c96d_idx'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['trainer', 'date'], name='fitx_class__trainer_8b9d5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waitlist',
            unique_together={('user', 'class_schedule')},
        ),
    ]
