import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'fitness.settings')
django.setup()

from workout.models import Exercise

workout_data = [
    # Strength - Beginner
    {"name": 'Push-ups', "category": 'strength', "exercise_type": 'beginner', "img": 'https://images.unsplash.com/photo-1598971639058-fab3c043d34d?w=400&q=80', "video": 'https://www.youtube.com/embed/IODxDxX7oi4', "reps": '3 Sets • 8-12 Reps', "burn": 50, "difficulty": 'Beginner', "steps": 'Place hands slightly wider than shoulders.\nKeep body in a straight line from head to heels.\nLower your chest to the floor.\nPush back to starting position.', "benefits": 'Chest development\nCore stability\nTricep strength', "mistakes": 'Hips sagging\nFlared elbows\nPartial reps'},
    {"name": 'Bodyweight Squats', "category": 'strength', "exercise_type": 'beginner', "img": 'https://images.unsplash.com/photo-1566241440091-ec10de8db2e1?w=400&q=80', "video": 'https://www.youtube.com/embed/m0GcZ24pK6k', "reps": '3 Sets • 15 Reps', "burn": 80, "difficulty": 'Beginner', "steps": 'Feet shoulder-width apart.\nKeep chest up and core engaged.\nLower hips as if sitting in a chair.\nPush through heels to stand up.', "benefits": 'Quad strength\nGlute activation\nMobility', "mistakes": 'Knees caving in\nRounding back\nLifting heels'},
    {"name": 'Glute Bridge', "category": 'strength', "exercise_type": 'beginner', "img": 'https://images.unsplash.com/photo-1590239062391-4ade36e6513d?w=400&q=80', "video": 'https://www.youtube.com/embed/wPM8icPu6H8', "reps": '3 Sets • 15 Reps', "burn": 60, "difficulty": 'Beginner', "steps": 'Lie on back, knees bent, feet flat.\nLift hips toward the ceiling.\nSqueeze glutes at the top.\nLower hips slowly.', "benefits": 'Glute isolation\nPostural support\nSpinal health', "mistakes": 'Arching lower back\nNot squeezing glutes'},
    {"name": 'Dumbbell Rows', "category": 'strength', "exercise_type": 'beginner', "img": 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&q=80', "video": 'https://www.youtube.com/embed/pYcpY20QaE8', "reps": '3 Sets • 10 Reps/Arm', "burn": 70, "difficulty": 'Beginner', "steps": 'Hold dumbbell in one hand.\nHinge at hips, keep back straight.\nPull dumbbell to your hip.\nLower it back down.', "benefits": 'Back strength\nPosture\nBiceps', "mistakes": 'Pulling with biceps\nJerking the weight'},
    {"name": 'Plank', "category": 'strength', "exercise_type": 'beginner', "img": 'https://images.unsplash.com/photo-1566241440091-ec10de8db2e1?w=400&q=80', "video": 'https://www.youtube.com/embed/pSHjTRCQxIw', "reps": '3 Sets • 30-45s', "burn": 40, "difficulty": 'Beginner', "steps": 'Place forearms on floor.\nKeep body in straight line.\nEngage core and glutes.\nHold position.', "benefits": 'Core endurance\nSpine stability', "mistakes": 'Hips dropping\nLooking up'},

    # Strength - Intermediate
    {"name": 'Barbell Lunges', "category": 'strength', "exercise_type": 'intermediate', "img": 'https://images.unsplash.com/photo-1434682772747-f16d3ea162c3?w=400&q=80', "video": 'https://www.youtube.com/embed/QOVaHwm-Q6U', "reps": '3 Sets • 12 Reps/Leg', "burn": 90, "difficulty": 'Intermediate', "steps": 'Barbell on back.\nStep forward with one leg.\nLower hips until both knees are 90 deg.\nPush back to start.', "benefits": 'Single leg balance\nLeg strength', "mistakes": 'Front knee over toes\nLeaning too far forward'},
    {"name": 'Overhead Press', "category": 'strength', "exercise_type": 'intermediate', "img": 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80', "video": 'https://www.youtube.com/embed/2yjwXTZEpVM', "reps": '3 Sets • 8-10 Reps', "burn": 75, "difficulty": 'Intermediate', "steps": 'Stand with barbell at collarbone.\nPress bar straight up.\nLock elbows at top.\nLower safely.', "benefits": 'Shoulder mass\nTricep strength', "mistakes": 'Arching back heavily'},
    {"name": 'Romanian Deadlift', "category": 'strength', "exercise_type": 'intermediate', "img": 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&q=80', "video": 'https://www.youtube.com/embed/JCXUYuzwNrM', "reps": '3 Sets • 10 Reps', "burn": 85, "difficulty": 'Intermediate', "steps": 'Hold barbell at hip level.\nPush hips back.\nLower bar to shins.\nSqueeze glutes to stand.', "benefits": 'Hamstring growth\nLower back resilience', "mistakes": 'Rounding the back'},
    {"name": 'Pull-ups', "category": 'strength', "exercise_type": 'intermediate', "img": 'https://images.unsplash.com/photo-1598971639058-fab3c043d34d?w=400&q=80', "video": 'https://www.youtube.com/embed/eGo4IYb0xMQ', "reps": '3 Sets • To Failure', "burn": 80, "difficulty": 'Intermediate', "steps": 'Hang from bar.\nPull chest to bar.\nLower with control.', "benefits": 'Lat width\nGrip strength', "mistakes": 'Kipping or swinging'},
    {"name": 'Bench Press', "category": 'strength', "exercise_type": 'intermediate', "img": 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80', "video": 'https://www.youtube.com/embed/rT7DgCr-3pg', "reps": '4 Sets • 8 Reps', "burn": 95, "difficulty": 'Intermediate', "steps": 'Lie on bench, grip bar.\nLower to mid-chest.\nPress up forcefully.', "benefits": 'Chest size\nPushing power', "mistakes": 'Bouncing bar off chest'},

    # Strength - Advanced
    {"name": 'Heavy Barbell Squats', "category": 'strength', "exercise_type": 'advanced', "img": 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80', "video": 'https://www.youtube.com/embed/SW_C1A-rejs', "reps": '4 Sets • 5 Reps', "burn": 180, "difficulty": 'Advanced', "steps": 'Barbell on traps.\nDrive hips back and down.\nKeep spine neutral.\nExplode upwards.', "benefits": 'Elite leg power\nHormonal response', "mistakes": 'Wink at bottom\nKnees caving'},
    {"name": 'Conventional Deadlift', "category": 'strength', "exercise_type": 'advanced', "img": 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80', "video": 'https://www.youtube.com/embed/op9kVnSso6Q', "reps": '4 Sets • 5 Reps', "burn": 190, "difficulty": 'Advanced', "steps": 'Stand mid-foot under bar.\nBend over, grab bar.\nDrop hips, lift chest.\nDrive through floor.', "benefits": 'Overall sheer strength\nPosterior chain', "mistakes": 'Jerking the bar'},
    {"name": 'Clean and Jerk', "category": 'strength', "exercise_type": 'advanced', "img": 'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=800&q=80', "video": 'https://www.youtube.com/embed/8miqQQJEsO0', "reps": '5 Sets • 3 Reps', "burn": 200, "difficulty": 'Advanced', "steps": 'Pull bar from floor.\nExplode and catch on shoulders.\nDip and press overhead.', "benefits": 'Explosive power\nCoordination', "mistakes": 'Poor bar path'},
    {"name": 'Muscle-ups', "category": 'strength', "exercise_type": 'advanced', "img": 'https://images.unsplash.com/photo-1598971639058-fab3c043d34d?w=800&q=80', "video": 'https://www.youtube.com/embed/Xce_BPGjeGM', "reps": '4 Sets • 5 Reps', "burn": 120, "difficulty": 'Advanced', "steps": 'Swing slightly on rings/bar.\nExplosive pull up.\nTransition chest over bar.\nDip to finish.', "benefits": 'Total upper body mastery\nCore control', "mistakes": 'Chicken winging one arm'},
    {"name": 'Weighted Dips', "category": 'strength', "exercise_type": 'advanced', "img": 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80', "video": 'https://www.youtube.com/embed/2z8JmcrW-As', "reps": '4 Sets • 8 Reps', "burn": 140, "difficulty": 'Advanced', "steps": 'Attach weight belt.\nSupport body on parallel bars.\nLower until shoulders below elbows.\nPress up.', "benefits": 'Huge triceps\nChest development', "mistakes": 'Not going deep enough'},

    # Yoga
    {"name": 'Surya Namaskar', "category": 'yoga', "exercise_type": 'all', "img": 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&q=80', "video": 'https://www.youtube.com/embed/iIDoI9-1nTo', "reps": '5 Rounds', "burn": 100, "difficulty": 'Intermediate', "steps": 'Pranamasana\nHastauttanasana\nPadahastasana\nAshwa Sanchalanasana', "benefits": 'Flexibility\nCirculation', "mistakes": 'Shallow breathing'},
    {"name": 'Downward Dog Vinyasa', "category": 'yoga', "exercise_type": 'all', "img": 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80', "video": 'https://www.youtube.com/embed/j97q5ZAjlJQ', "reps": '10 Mins', "burn": 80, "difficulty": 'Beginner', "steps": 'Start in plank.\nPush hips back and up.\nPedal feet.', "benefits": 'Calf stretch\nShoulder mobility', "mistakes": 'Rounded upper back'},
    {"name": 'Warrior Sequence', "category": 'yoga', "exercise_type": 'all', "img": 'https://images.unsplash.com/photo-1597452485677-d661670d9640?w=400&q=80', "video": 'https://www.youtube.com/embed/iIDoI9-1nTo', "reps": '3 Sets • 1 Min Hold', "burn": 90, "difficulty": 'Intermediate', "steps": 'Lunge position.\nBack foot 45 degrees.\nArms extended.', "benefits": 'Leg endurance\nFocus', "mistakes": 'Knee collapsing inward'},
    {"name": 'Crow Pose', "category": 'yoga', "exercise_type": 'all', "img": 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=400&q=80', "video": 'https://www.youtube.com/embed/iIDoI9-1nTo', "reps": '5 Attempts', "burn": 50, "difficulty": 'Advanced', "steps": 'Squat down.\nHands flat on floor.\nKnees to triceps.\nLean forward and lift feet.', "benefits": 'Arm balance\nCore compression', "mistakes": 'Looking down instead of forward'},
    {"name": 'Chaturanga to Up-Dog', "category": 'yoga', "exercise_type": 'all', "img": 'https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?w=400&q=80', "video": 'https://www.youtube.com/embed/iIDoI9-1nTo', "reps": '10 Reps', "burn": 70, "difficulty": 'Intermediate', "steps": 'Plank to low push-up.\nFlip feet, push chest up.\nLook upward.', "benefits": 'Triceps\nSpinal extension', "mistakes": 'Dumping weight in lower back'},

    # HIIT Core
    {"name": 'Mountain Climbers', "category": 'hiit', "exercise_type": 'core', "img": 'https://images.unsplash.com/photo-1598971639058-fab3c043d34d?w=400&q=80', "video": 'https://www.youtube.com/embed/IODxDxX7oi4', "reps": '45s Work • 15s Rest', "burn": 80, "difficulty": 'Beginner', "steps": 'Plank position\nAlternating knees to chest rapidly', "benefits": 'Core\nStamina', "mistakes": 'Bouncing hips'},
    {"name": 'Bicycle Crunches', "category": 'hiit', "exercise_type": 'core', "img": 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&q=80', "video": 'https://www.youtube.com/embed/9FGilxCbdz8', "reps": '40s Work • 20s Rest', "burn": 70, "difficulty": 'Intermediate', "steps": 'Lie on back.\nBring opposite elbow to knee.\nPedal legs.', "benefits": 'Obliques\nAbs', "mistakes": 'Pulling the neck'},
    {"name": 'Hollow Body Rocks', "category": 'hiit', "exercise_type": 'core', "img": 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&q=80', "video": 'https://www.youtube.com/embed/pSHjTRCQxIw', "reps": '30s Work • 15s Rest', "burn": 50, "difficulty": 'Advanced', "steps": 'Lie back, limbs extended.\nLift shoulders and legs.\nRock back and forth.', "benefits": 'Deep core control', "mistakes": 'Lower back arching'},
    {"name": 'Russian Twists', "category": 'hiit', "exercise_type": 'core', "img": 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&q=80', "video": 'https://www.youtube.com/embed/wkD8rjkodUI', "reps": '40s Work', "burn": 60, "difficulty": 'Intermediate', "steps": 'Sit up, tilt back 45deg.\nTwist torso side to side.', "benefits": 'Rotational strength', "mistakes": 'Just moving arms'},
    {"name": 'V-Ups', "category": 'hiit', "exercise_type": 'core', "img": 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80', "video": 'https://www.youtube.com/embed/iIDoI9-1nTo', "reps": '30s Work', "burn": 65, "difficulty": 'Advanced', "steps": 'Lie flat.\nLift legs and torso simultaneously.\nTouch toes.', "benefits": 'Total abdominals', "mistakes": 'Bending knees excessively'},

    # HIIT Fullbody
    {"name": 'Burpees', "category": 'hiit', "exercise_type": 'fullbody', "img": 'https://images.unsplash.com/photo-1533681904393-9ab6eee7e408?w=400&q=80', "video": 'https://www.youtube.com/embed/TU8QYVW0gDU', "reps": '40s Work • 20s Rest', "burn": 120, "difficulty": 'Intermediate', "steps": 'Squat down.\nKick feet back to plank.\nDo a push-up.\nJump up.', "benefits": 'Cardio\nFull body power', "mistakes": 'Sagging hips in plank'},
    {"name": 'Kettlebell Swings', "category": 'hiit', "exercise_type": 'fullbody', "img": 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=400&q=80', "video": 'https://www.youtube.com/embed/YSxHifyI6s8', "reps": '45s Work', "burn": 110, "difficulty": 'Intermediate', "steps": 'Hinge at hips.\nSwing bell between legs.\nThrust hips to swing bell up.', "benefits": 'Glute power\nConditioning', "mistakes": 'Squatting instead of hinging'},
    {"name": 'Jumping Lunges', "category": 'hiit', "exercise_type": 'fullbody', "img": 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&q=80', "video": 'https://www.youtube.com/embed/QOVaHwm-Q6U', "reps": '30s Work', "burn": 90, "difficulty": 'Advanced', "steps": 'Lunge position.\nExplode up and switch legs.\nLand softly.', "benefits": 'Agility\nPlyometrics', "mistakes": 'Hard landings'},
    {"name": 'Battle Ropes', "category": 'hiit', "exercise_type": 'fullbody', "img": 'https://images.unsplash.com/photo-1599058945522-28d584b6f4ff?w=400&q=80', "video": 'https://www.youtube.com/embed/eGo4IYb0xMQ', "reps": '30s Work', "burn": 100, "difficulty": 'Beginner', "steps": 'Quarter squat.\nWhip ropes up and down rapidly.', "benefits": 'Shoulder endurance\nHeart rate', "mistakes": 'Standing too straight'},
    {"name": 'Box Jumps', "category": 'hiit', "exercise_type": 'fullbody', "img": 'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=400&q=80', "video": 'https://www.youtube.com/embed/52r_Ul5k03g', "reps": '40s Work', "burn": 130, "difficulty": 'Intermediate', "steps": 'Stand facing box.\nQuarter squat, swing arms.\nJump onto box, land soft.\nStep down.', "benefits": 'Explosiveness\nLeg power', "mistakes": 'Jumping down instead of stepping down'},

    # Home Basics
    {"name": 'Classic Push-ups', "category": 'home', "exercise_type": 'basics', "img": 'https://images.unsplash.com/photo-1598971639058-fab3c043d34d?w=400&q=80', "video": 'https://www.youtube.com/embed/IODxDxX7oi4', "reps": '3 Sets • 10-15 Reps', "burn": 60, "difficulty": 'Beginner', "steps": 'Standard push-up motion.', "benefits": 'Chest\nTriceps', "mistakes": 'Flaring elbows'},
    {"name": 'Tricep Dips on Chair', "category": 'home', "exercise_type": 'basics', "img": 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80', "video": 'https://www.youtube.com/embed/2z8JmcrW-As', "reps": '3 Sets • 12 Reps', "burn": 50, "difficulty": 'Beginner', "steps": 'Hands on chair edge.\nLower body down.\nPress back up.', "benefits": 'Triceps isolated', "mistakes": 'Shoulders rolling forward'},
    {"name": 'Wall Sit', "category": 'home', "exercise_type": 'basics', "img": 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&q=80', "video": 'https://www.youtube.com/embed/m0GcZ24pK6k', "reps": '3 Sets • 45s Hold', "burn": 40, "difficulty": 'Beginner', "steps": 'Back flat against wall.\nKnees at 90 degrees.\nHold.', "benefits": 'Quad endurance', "mistakes": 'Hands on knees'},
    {"name": 'Pike Push-ups', "category": 'home', "exercise_type": 'basics', "img": 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=400&q=80', "video": 'https://www.youtube.com/embed/IODxDxX7oi4', "reps": '3 Sets • 8-10 Reps', "burn": 70, "difficulty": 'Intermediate', "steps": 'Downward dog position.\nBend elbows, lower head.\nPush back.', "benefits": 'Shoulder strength', "mistakes": 'Elbows flaring extremely wide'},
    {"name": 'Single-Leg Glute Bridges', "category": 'home', "exercise_type": 'basics', "img": 'https://images.unsplash.com/photo-1590239062391-4ade36e6513d?w=400&q=80', "video": 'https://www.youtube.com/embed/wPM8icPu6H8', "reps": '3 Sets • 12 Reps/Leg', "burn": 65, "difficulty": 'Intermediate', "steps": 'Bridge up with one leg extended.\nSqueeze glute.', "benefits": 'Glute isolation', "mistakes": 'Lower back over-arching'},
    
    # Home Cardio
    {"name": 'Jumping Jacks', "category": 'home', "exercise_type": 'cardio', "img": 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=400&q=80', "video": 'https://www.youtube.com/embed/iIDoI9-1nTo', "reps": '3 Mins', "burn": 40, "difficulty": 'Beginner', "steps": 'Standard jumping jack.', "benefits": 'Warm-up\nHeart rate', "mistakes": 'Lazy arm movement'},
    {"name": 'High Knees', "category": 'home', "exercise_type": 'cardio', "img": 'https://images.unsplash.com/photo-1485727749690-d091e8284ef3?w=400&q=80', "video": 'https://www.youtube.com/embed/iIDoI9-1nTo', "reps": '45s Work', "burn": 60, "difficulty": 'Intermediate', "steps": 'Run in place.\nLift knees high.', "benefits": 'Hip flexors\nCardio', "mistakes": 'Leaning back'},
    {"name": 'Jump Rope (Simulated)', "category": 'home', "exercise_type": 'cardio', "img": 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&q=80', "video": 'https://www.youtube.com/embed/iIDoI9-1nTo', "reps": '2 Mins', "burn": 50, "difficulty": 'Beginner', "steps": 'Bounce lightly.\nRotate wrists.', "benefits": 'Calves\nCardio', "mistakes": 'Jumping too high'},
    {"name": 'Skater Jumps', "category": 'home', "exercise_type": 'cardio', "img": 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&q=80', "video": 'https://www.youtube.com/embed/iIDoI9-1nTo', "reps": '1 Min', "burn": 70, "difficulty": 'Intermediate', "steps": 'Leap laterally side to side.', "benefits": 'Lateral agility', "mistakes": 'Not bending knee on landing'},
    {"name": 'Tuck Jumps', "category": 'home', "exercise_type": 'cardio', "img": 'https://images.unsplash.com/photo-1507398941214-572c25f4b1dc?w=400&q=80', "video": 'https://www.youtube.com/embed/52r_Ul5k03g', "reps": '30s Work', "burn": 80, "difficulty": 'Advanced', "steps": 'Jump up.\nTuck knees to chest.\nLand soft.', "benefits": 'Explosive leg power', "mistakes": 'Landing stiff-legged'},
]

Exercise.objects.all().delete()
for ed in workout_data:
    Exercise.objects.create(
        name=ed['name'],
        category=ed['category'],
        exercise_type=ed['exercise_type'],
        difficulty=ed['difficulty'],
        reps_sets=ed['reps'],
        calories_burned=ed['burn'],
        video_url=ed['video'],
        image_url=ed['img'],
        steps=ed['steps'],
        benefits=ed['benefits'],
        mistakes=ed['mistakes']
    )

print("Successfully seeded 40 exercises.")
