# Generated by Django 6.0.2 on 2026-03-25 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otpverification'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('user', 'Regular User'), ('trainer', 'Trainer'), ('nutritionist', 'Nutritionist'), ('admin', 'Administrator'), ('support', 'Support Staff'), ('content_manager', 'Content Manager')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=dict, help_text='Granular permissions map')),
            ],
            options={
                'db_table': 'fitx_roles',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fitx_user_roles',
            },
        ),
        migrations.AlterModelOptions(
            name='fitnessprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='otp',
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('active', 'Very Active'), ('extreme', 'Extremely Active')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Comma-separated allergens'),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='body_fat_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='dietary_preference',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='membership_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=15),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='total_workouts_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessprofile',
            name='xp_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='otp_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='fitnessprofile',
            name='fitness_goal',
            field=models.CharField(choices=[('muscle_gain', 'Muscle Gain'), ('fat_loss', 'Fat Loss'), ('weight_loss', 'Weight Loss'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('maintenance', 'Maintenance'), ('general_fitness', 'General Fitness')], default='general_fitness', max_length=50),
        ),
        migrations.AlterField(
            model_name='fitnessprofile',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='fitnessprofile',
            index=models.Index(fields=['membership_type', 'membership_expires_at'], name='fitx_users_members_7b8523_idx'),
        ),
        migrations.AddIndex(
            model_name='fitnessprofile',
            index=models.Index(fields=['city'], name='fitx_users_city_14fc74_idx'),
        ),
        migrations.AddIndex(
            model_name='fitnessprofile',
            index=models.Index(fields=['fitness_goal'], name='fitx_users_fitness_a2840f_idx'),
        ),
        migrations.AlterModelTable(
            name='fitnessprofile',
            table='fitx_users',
        ),
        migrations.AlterModelTable(
            name='otpverification',
            table='fitx_otp',
        ),
        migrations.AddField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='fitx_user_r_user_id_9a2178_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
