# Generated by Django 6.0.2 on 2026-03-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_account', '0004_role_userrole_alter_fitnessprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
