# Generated by Django 6.0.2 on 2026-03-21 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('yoga', 'Yoga & Mind'), ('hiit', 'HIIT / Cardio'), ('home', 'At Home')], max_length=50)),
                ('exercise_type', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('core', 'Core'), ('fullbody', 'Full Body'), ('basics', 'Bodyweight Basics'), ('cardio', 'Cardio Blast'), ('all', 'All Levels')], max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('reps_sets', models.CharField(max_length=100)),
                ('calories_burned', models.PositiveIntegerField()),
                ('video_url', models.URLField(blank=True, help_text='YouTube Embed URL', null=True)),
                ('image_url', models.URLField(blank=True, help_text='Unsplash URL for placeholder', null=True)),
                ('steps', models.TextField(help_text='Separate steps with newlines')),
                ('benefits', models.TextField(help_text='Separate benefits with newlines')),
                ('mistakes', models.TextField(help_text='Separate mistakes with newlines')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
