# Generated by Django 6.0.2 on 2026-03-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_exercise_userroutine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardio'), ('hiit', 'HIIT'), ('yoga', 'Yoga'), ('home', 'Home Workout'), ('flexibility', 'Flexibility and mobility')], max_length=50),
        ),
    ]
