# Generated by Django 6.0.2 on 2026-03-25 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_exercise_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('specializations', models.JSONField(default=list)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('certifications', models.JSONField(default=list)),
                ('bio', models.TextField(max_length=1000)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('intro_video_url', models.URLField(blank=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_sessions_conducted', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('max_daily_sessions', models.PositiveIntegerField(default=8)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fitx_trainer_profiles',
            },
        ),
        migrations.CreateModel(
            name='TrainerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='workout.trainerprofile')),
            ],
            options={
                'db_table': 'fitx_trainer_availability',
            },
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['verification_status', 'is_available'], name='fitx_traine_verific_ebd7c8_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['average_rating'], name='fitx_traine_average_957874_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='traineravailability',
            unique_together={('trainer', 'day_of_week', 'start_time')},
        ),
    ]
