# Generated by Django 6.0.2 on 2026-03-25 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_mealplan_breakfast_mealplan_dinner_mealplan_lunch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('weight', 'Weight Goal'), ('workout', 'Workout Count'), ('streak', 'Streak'), ('custom', 'Custom Goal')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(default=0)),
                ('achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fitx_goal_milestones',
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('angle', models.CharField(choices=[('front', 'Front'), ('side', 'Side'), ('back', 'Back')], default='front', max_length=10)),
                ('image', models.ImageField(upload_to='progress_photos/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fitx_progress_photos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField(help_text='kg')),
                ('body_fat_percentage', models.FloatField(blank=True, null=True)),
                ('chest', models.FloatField(blank=True, help_text='cm', null=True)),
                ('waist', models.FloatField(blank=True, help_text='cm', null=True)),
                ('hips', models.FloatField(blank=True, help_text='cm', null=True)),
                ('biceps', models.FloatField(blank=True, help_text='cm', null=True)),
                ('thighs', models.FloatField(blank=True, help_text='cm', null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fitx_body_measurements',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
