# Generated by Django 6.0.2 on 2026-04-03 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_goalmilestone_progressphoto_bodymeasurement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('goal_type', models.CharField(choices=[('any', 'Any Goal'), ('weight_loss', 'Weight Loss'), ('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('endurance', 'Endurance'), ('general_fitness', 'General Fitness')], default='any', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('dietary_type', models.CharField(choices=[('veg', 'Vegetarian'), ('egg', 'Eggetarian'), ('nonveg', 'Non-Vegetarian')], default='veg', max_length=10)),
                ('target_calories_min', models.PositiveIntegerField(default=1200)),
                ('target_calories_max', models.PositiveIntegerField(default=3500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fitx_diet_plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the meal')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('dietary_type', models.CharField(choices=[('veg', 'Vegetarian'), ('egg', 'Eggetarian'), ('nonveg', 'Non-Vegetarian')], default='veg', max_length=10)),
                ('goal_tag', models.CharField(choices=[('any', 'Any Goal'), ('weight_loss', 'Weight Loss'), ('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('endurance', 'Endurance'), ('general_fitness', 'General Fitness')], default='any', help_text='Which fitness goal this meal suits best', max_length=30)),
                ('calories', models.PositiveIntegerField(help_text='kcal per serving')),
                ('protein', models.FloatField(help_text='grams')),
                ('carbs', models.FloatField(help_text='grams')),
                ('fats', models.FloatField(help_text='grams')),
                ('fiber', models.FloatField(default=0, help_text='grams')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to exclude from recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fitx_meals',
                'ordering': ['meal_type', 'name'],
                'indexes': [models.Index(fields=['meal_type', 'dietary_type'], name='fitx_meals_meal_ty_9b4e25_idx'), models.Index(fields=['goal_tag'], name='fitx_meals_goal_ta_600764_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_calories', models.PositiveIntegerField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fats', models.FloatField(default=0)),
                ('breakfast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_breakfasts', to='diet.meal')),
                ('dinner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_dinners', to='diet.meal')),
                ('lunch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_lunches', to='diet.meal')),
                ('snack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_snacks', to='diet.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_diets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fitx_user_diets',
                'ordering': ['id'],
                'unique_together': {('user', 'day_of_week', 'generated_at')},
            },
        ),
    ]
