# Generated by Django 6.0.2 on 2026-03-25 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('category', models.CharField(max_length=50)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('criteria', models.JSONField(help_text='Example: {"type": "streak", "value": 7}')),
            ],
            options={
                'db_table': 'fitx_badges',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20)),
                ('metric', models.CharField(choices=[('xp', 'XP Points'), ('workouts', 'Workouts Completed'), ('calories', 'Calories Burned'), ('streak', 'Longest Streak')], max_length=20)),
                ('value', models.FloatField(default=0)),
                ('rank', models.PositiveIntegerField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fitx_leaderboard',
                'indexes': [models.Index(fields=['period', 'metric', 'rank'], name='fitx_leader_period_b974ed_idx')],
                'unique_together': {('user', 'period', 'metric')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fitx_user_badges',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
